# Generated by Django 4.2.9 on 2026-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='curriculum',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
